name: Publish GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Cobalt
        run: |
          curl -LSfs https://raw.githubusercontent.com/crate-ci/gh-install/master/v1/install.sh | \
            sh -s -- \
            --git cobalt-org/cobalt.rs \
            --crate cobalt \
            --force \
            --target x86_64-unknown-linux-gnu \
            --tag v0.20.4
          echo COBALT_BIN=~/.cargo/bin/cobalt >> $GITHUB_ENV

      - name: Build site
        run: ${{ env.COBALT_BIN }} build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
